# Generated by Django 4.0.1 on 2022-01-11 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Cedula', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Dereccion', models.CharField(max_length=300)),
                ('Telefono', models.CharField(max_length=10)),
                ('FechaNacimiento', models.DateField()),
                ('Genero', models.BooleanField()),
                ('Nombre', models.CharField(max_length=30)),
                ('PrimerApellido', models.CharField(max_length=30)),
                ('SegundoApellido', models.CharField(max_length=30)),
                ('Correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EncabezadoOrdenVenta',
            fields=[
                ('IdOrdenVenta', models.AutoField(primary_key=True, serialize=False)),
                ('IdSupermercado', models.CharField(max_length=15)),
                ('TipoCambio', models.IntegerField(default=1)),
                ('FechaOrden', models.DateField()),
                ('IdPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventaxpersona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenVenta',
            fields=[
                ('IdLinea', models.AutoField(primary_key=True, serialize=False)),
                ('IdProducto', models.IntegerField()),
                ('NombreProdcuto', models.CharField(max_length=50)),
                ('Unidad', models.CharField(max_length=50)),
                ('PrecioUnit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('PorcentajeImp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('PrecioImpUnit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Cantidad', models.IntegerField()),
                ('PrecioTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('IdOrdenVenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ventaxpersona.encabezadoordenventa')),
            ],
        ),
    ]
