# Generated by Django 4.0.1 on 2022-01-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventaxpersona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encabezadoordenventa',
            name='MetodoPago',
            field=models.CharField(choices=[('Dolares', 'Dolares de agrega el tipo de cambio'), ('Colones', 'colones se agrega un 1')], default='Colones', max_length=32),
        ),
    ]
